name: Build and Push Docker Image on processing_requests registry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run Flake8
        run: |
          flake8 --max-line-length 99  
        continue-on-error: false

      - name: Run tests
        run: |
          python -m unittest -v tests/processing_requests_unittest.py
        continue-on-error: false

      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/processing_requests/Dockerfile

      - name: Set Version
        run: |
          echo "DOCKER_IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}:${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: "${{ secrets.PROCESSING_REQUESTS_PATH }}/Dockerfile"
          directory: ${{ secrets.PROCESSING_REQUESTS_PATH }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          image: ${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}
          registry: docker.io
          tags: "${{ vars.PROCESSING_REQUESTS_VERSION }}.${{ github.run_number }}"
