name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a Docker tag
        options: ${{ fromJSON(needs.fetch-tags.outputs.artifacts.docker-tags) }}

jobs:
  build:
    needs: fetch-tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show available tags
        run: |
          DOCKER_TAGS=$(<docker_tags.txt)
          echo "Available Docker tags:"
          echo "$DOCKER_TAGS"
