name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Choose a Docker tag'
        options:
          - $(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}/tags" | jq -r '.results[].name')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: get-tags
        run: |
          DOCKER_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}/tags" | jq -r '.results[].name')
          echo "::set-output name=tags::$DOCKER_TAGS"

      - name: Choose Docker tag
        run: echo "Chosen tag is ${{ github.event.inputs.choice }}"
