name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose a Docker tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker tag choices
        id: docker-tag-choices
        run: |
          TAG_CHOICES=$(echo "${{ steps.get-tags.outputs.tags }}" | sed 's/^/- /')
          echo "::set-output name=tag-choices::$TAG_CHOICES"
