name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose a Docker tag
        options: ${{ steps.get-tags.outputs.tag-choices }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: get-tags
        run: |
          DOCKER_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}/tags" | jq -r '.results[].name')
          TAG_CHOICES=$(echo "$DOCKER_TAGS" | sed 's/^/- /')
          echo "::set-output name=tag-choices::$TAG_CHOICES"

      - name: Show available tags
        run: |
          echo "Available Docker tags:"
          echo "$DOCKER_TAGS"
