name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose a Docker tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: get-tags
        run: |
          DOCKER_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}/tags" | jq -r '.results[].name')
          echo "::set-output name=tags::$DOCKER_TAGS"

      - name: Set up Docker tag choices
        id: docker-tag-choices
        run: |
          TAG_CHOICES=$(echo "${{ steps.get-tags.outputs.tags }}" | sed 's/^/- /')
          echo "::set-output name=tag-choices::$TAG_CHOICES"

      - name: Choose Docker tag
        run: |
          echo "Available tags:"
          echo "${{ steps.docker-tag-choices.outputs.tag-choices }}"
          echo "Chosen tag is ${{ github.event.inputs.choice }}"
