name: Fetch Docker Tags

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  fetch-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker tags
        id: get-tags
        run: |
          DOCKER_TAGS=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_IMAGE_PROCESSING_REQUEST }}/tags" | jq -r '.results[].name')
          echo "$DOCKER_TAGS" > docker_tags.txt

      - name: Upload Docker tags as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-tags
          path: docker_tags.txt
